### ISSUE TITLE
You have wrong tags

### ISSUE THREAD

**Issue by pranayteaches** [velansalis/brailler#1]
Hi this is a good repo, but I have something to say.
This not an NLP project its somewhat related to that but can not be considered as an NLP project. I will suggest you to remove the NLP tag, you may use other tags.
thank you

**Comment by velansalis** [comment]
Hey. Thanks a lot for bringing it to my attention. My bad, Should have paid a little attention when writing one :)

**Comment by pranayteaches** [comment]
cool. I am glad you noticed that
